{% set name = "virga-exo" %}
{% set version = "2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1bb767923ff333535f317ec469a35d03e37c40e1843f61832d53ff9d9a5764ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - bokeh
    - astropy-base
    - scipy <1.14
    - miepython
    - matplotlib-base

test:
  imports:
    - virga
    - virga.justdoit
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://natashabatalha.github.io/virga
  summary: substellar atmosphere code for computing clouds
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholaswogan
    - natashabatalha
